export type Side = "l" | "r";
export interface Msg { from: string; side: Side; text: string; img?: boolean; }
export interface Choice { text: string; fb: string; tone: "good" | "mid" | "bad"; }
export interface Chapter {
  id: string;
  place: string;
  title: string;
  domain: string;
  msgs: Msg[];
  ask: string;
  choices: Choice[];
  reflect: string;
}

export const SCENARIOS: Chapter[] = [
  {
    id: "ch1",
    place: "Grup Panitia · Media Sosial",
    title: "Caption-nya gimana?",
    domain: "CONTEXT AWARENESS",
    msgs: [
      { from: "Alya", side: "l", text: "Guys, poster acara kita udah jadi." },
      { from: "Raka", side: "l", text: "Captionnya deh sekalian, siapa yang mau bikin?" },
      { from: "Naya", side: "l", text: "Gue aja dehh" },
      { from: "Naya", side: "l", text: "Finally, our project is done! Proud of what we created together." },
      { from: "Alya", side: "l", text: "Ok juga tuh" },
      { from: "Raka", side: "l", text: "Tapi kenapa Inggris semua?" },
      { from: "Naya", side: "l", text: "Gatau jujur.. tapi aneh ga sih kalo Bahasa Indonesia semua? kaya kurang keren aja gituuu😭" },
      { from: "Alya", side: "l", text: "Kurang keren gimana? kita kan pake Bahasa Indonesia juga yah..." },
      { from: "Naya", side: "l", text: "Eh. Iya juga sih..." },
    ],
    ask: "Kalau kamu ikut dalam percakapan itu, keputusan mana yang paling tepat sebelum mereka menentukan caption final?",
    choices: [
      { text: "Kalau caption Bahasa Inggris terasa lebih sesuai dengan gaya konten yang biasa dilihat anak muda sekarang, menurutku tidak masalah digunakan. Yang penting pesannya tetap mudah dipahami.", tone: "mid",
        fb: "Alasan ini masuk akal — gaya konten anak muda memang layak dipertimbangkan. Tapi coba perhatikan: alasannya datang dari luar, dari apa yang biasa dilihat, bukan dari konteks kalian sendiri. Kalau alasan utamanya cuma mengikuti yang sering muncul di timeline, sebenarnya kita belum benar-benar memilih." },
      { text: "Menurutku jangan langsung mengganti semuanya. Kita bisa lihat dulu siapa yang akan membaca unggahan ini dan apa tujuan caption-nya. Dari situ baru diputuskan bahasa mana yang paling tepat.", tone: "good",
        fb: "Menariknya, kamu tidak langsung memilih bahasa.\n\nKamu memilih untuk mencari alasan di balik pilihan bahasa tersebut.\n\nKarena sebenarnya ada dua pertanyaan berbeda:\n\n\u201CBahasa mana yang mau kita pakai?\u201D\ndan\n\u201CKenapa kita memilih bahasa itu?\u201D\n\nPertanyaan kedua jauh lebih penting.\n\nNaya mengatakan Bahasa Indonesia terasa \u201Ckurang keren\u201D.\n\nTapi kalau ditanya: \u201CKurang keren karena apa?\u201D — belum tentu ada jawabannya.\n\nBisa jadi karena terbiasa melihat konten berbahasa Inggris. Bisa jadi karena bahasa Inggris dianggap lebih modern. Bisa jadi karena lingkungan pertemanan membentuk anggapan tersebut. Atau memang karena konteks caption-nya membutuhkan gaya tertentu.\n\nJadi persoalannya bukan Bahasa Inggris boleh atau tidak.\n\nYang perlu mulai dipikirkan adalah: \u201CApakah gue memilih bahasa ini karena memang sesuai, atau karena gue sudah menganggap bahasa tertentu lebih keren?\u201D" },
      { text: "Karena ini kegiatan sekolah dan menggunakan Bahasa Indonesia dalam acaranya, sebaiknya caption dibuat dalam Bahasa Indonesia. Bahasa Inggris bisa digunakan kalau memang ada bagian yang diperlukan.", tone: "mid",
        fb: "Alasan \u201Cini kegiatan sekolah\u201D kuat dan bisa dipertanggungjawabkan. Tapi coba cek lagi: apakah semua caption kegiatan sekolah harus sepenuhnya Bahasa Indonesia? Justru pertanyaan \u201Ckapan Bahasa Inggris diperlukan?\u201D itu yang belum pernah dibahas sama-sama — padahal kebingungan Naya ada di situ." },
      { text: "Menurutku campur saja keduanya. Bahasa Indonesia bisa menyampaikan informasi, sedangkan Bahasa Inggris bisa membuat caption terasa lebih menarik dan dekat dengan gaya media sosial.", tone: "mid",
        fb: "Campuran bahasa memang gaya yang umum sekarang dan tidak otomatis salah. Tapi pilihan ini langsung melompat ke solusi tanpa menjawab kebingungan Naya — padahal dia baru saja bilang Bahasa Indonesia terasa \u201Ckurang keren\u201D. Kalau dibiarkan tanpa dibahas, anggapan itu tetap tertanam, apa pun caption finalnya nanti." },
    ],
    reflect: "Kalau ditanya jujur, \u201Ckurang keren karena apa?\u201D — apa jawabanmu untuk Naya?",
  },
  {
    id: "ch2",
    place: "Grup Kelas · Sore Harusnya Santai",
    title: "Harus Formal?",
    domain: "CONTEXT AWARENESS",
    msgs: [
      { from: "Raka", side: "l", text: "GUYS, Bu Rani baru masuk grup ya?." },
      { from: "Naya", side: "l", text: "HAH? emang iya?" },
      { from: "Alya", side: "l", text: "Kok panik euy?😭" },
      { from: "Naya", side: "l", text: "Tadi gue baru nulis 'besok gas jam 3 ya, jangan ngilang'." },
      { from: "Raka", side: "l", text: "Santai bener yak ketikannya wkwkwk." },
      { from: "Naya", side: "l", text: "Apa gue edit aja ya chat nya..mumpung masih bisa diedit, biar lebih sopan gitu pas dibaca Bu Rani" },
      { from: "Raka", side: "l", text: "Boleeh. Edit total aja kali ya? Biar aman." },
      { from: "Alya", side: "l", text: "Emang harus berubah total?" },
      { from: "Naya", side: "l", text: "Iya..(?) kan sekarang di grup udah ada Bu Rani yah" },
      { from: "Raka", side: "l", text: "Diedit jadi lebih formal aja, Nay.." },
      { from: "Alya", side: "l", text: "Emang kalo nge-chat guru harus formal banget ya?" },
      { from: "Naya", side: "l", text: "Duhh terus ini yang bener gimanaa? 😞" },
    ],
    ask: "Kalau kamu ada di situasi tersebut, respons mana yang paling tepat?",
    choices: [
      { text: "Kalau sudah ada guru, sebaiknya semua percakapan dibuat formal supaya tidak menimbulkan kesan kurang sopan.", tone: "mid",
        fb: "Kehati-hatianmu masuk akal — memang ada guru yang ikut membaca. Tapi \u201Csemua harus formal\u201D itu jalan pintas: grup ini tetap grup pertemanan, cuma sekarang ada Bu Rani di dalamnya. Kalau semua chat mendadak kaku, yang terasa janggal justru buatan-buatannya — dan Bu Rani bisa merasakan itu." },
      { text: "Menurutku tidak perlu mengubah seluruh cara bicara. Kita cukup menyesuaikan pilihan kata dengan siapa yang sedang diajak bicara dan tujuan percakapannya.", tone: "good",
        fb: "Ternyata menyesuaikan bahasa tidak selalu berarti mengubah cara bicara menjadi sangat formal.\n\nCara kita berbicara dengan teman dekat tentu bisa berbeda dengan cara kita berbicara kepada guru.\n\nTetapi perbedaan itu tidak berarti satu harus selalu santai dan yang lain harus selalu kaku.\n\nYang perlu diperhatikan adalah: siapa yang diajak bicara, situasinya seperti apa, dan apa yang ingin disampaikan.\n\nBahasa yang baik bukan berarti selalu menggunakan kata-kata paling formal.\n\nBahasa yang baik adalah bahasa yang sesuai dengan situasinya." },
      { text: "Lebih baik tetap menggunakan gaya bicara seperti sebelumnya supaya percakapannya tidak terasa dibuat-buat.", tone: "mid",
        fb: "Alasan \u201Cbiar tidak dibuat-buat\u201D juga bisa dipahami. Tapi ada bedanya antara tetap santai dan mengabaikan siapa yang membaca. Chat \u201Cjangan ngilang\u201D ke teman itu wajar — kalau isinya mengajak kegiatan yang butuh kejelasan dan Bu Rani ikut membaca, kalimatnya perlu penyesuaian kecil, bukan dibiarkan total." },
      { text: "Kalau ingin tetap sopan tetapi tidak terlalu kaku, sebaiknya gunakan Bahasa Indonesia dengan istilah-istilah yang lebih modern.", tone: "mid",
        fb: "Nadanya tetap sopan dan idenya modern — tidak salah. Tapi \u201Cistilah modern\u201D bukan penentu kesopanan. Bisa jadi tetap terdengar kasar, bisa jadi juga tidak. Yang menentukan tetap sama: siapa lawan bicaranya, dan apa yang mau disampaikan." },
    ],
    reflect: "Kalau besoknya Bu Rani keluar dari grup, apakah chat-mu akan kembali seperti semula? Kenapa?",
  },
  {
    id: "ch3",
    place: "Grup Panitia · Malem",
    title: "Emang kalau resmi berarti benar?",
    domain: "LANGUAGE NORM AWARENESS",
    msgs: [
      { from: "Raka", side: "l", text: "Guys, teks pengumumannya udah ada belum?" },
      { from: "Naya", side: "l", text: "Udah gue bikin tadi." },
      { from: "Alya", side: "l", text: "Mana?" },
      { from: "Naya", side: "l", text: "Ini, tinggal masukin ke poster." },
      { from: "Naya", side: "l", text: "PEMBERITAHUAN\n\nDalam rangka meningkatkan partisipasi dan kedisiplinan seluruh peserta didik dalam mengikuti kegiatan sekolah, maka diberitahukan kepada seluruh siswa-siswi MAN Kotawaringin Timur bahwa akan dilaksanakan kegiatan Pekan Kreativitas dan Literasi Sekolah yang akan dilaksanakan pada:\n\nHari/Tanggal : Senin, 14 September 2026\nWaktu : 07.30 WIB s.d. selesai\nTempat : Lapangan Utama Madrasah\n\nSehubungan dengan hal tersebut, kepada seluruh siswa-siswi diwajibkan untuk dapat mengikuti kegiatan tersebut dengan tertib dan tepat waktu serta menggunakan pakaian sesuai dengan ketentuan yang telah ditetapkan oleh pihak madrasah. Bagi peserta didik yang berhalangan hadir dikarenakan sesuatu hal, diharapkan agar dapat memberikan keterangan kepada wali kelas masing-masing.\n\nDemikian pemberitahuan ini disampaikan untuk dapat diketahui dan dilaksanakan sebagaimana mestinya. Atas perhatian dan kerjasamanya kami ucapkan terimakasih." },
      { from: "Naya", side: "l", text: "Udah kan? Tinggal input aja ke poster." },
      { from: "Raka", side: "l", text: "Etdah, cepet banget nay😭" },
      { from: "Naya", side: "l", text: "Hehe, biasalaah aku minta bantuan AI. Terus bahasanya udah baku tuh, teks nya panjang juga, keliatannya juga resmi banget. Udah pasti bener ah." },
      { from: "Alya", side: "l", text: "Loh… emang kalau bahasanya baku dan resmi berarti udah bener kah? 😭" },
      { from: "Naya", side: "l", text: "Ya… harusnya?" },
      { from: "Alya", side: "l", text: "Check lagi deh. Kalau teks pengumumannya salah nanti Kepsek kita marah lo 😭" },
      { from: "Naya", side: "l", text: "..." },
      { from: "Raka", side: "l", text: "Waduh." },
    ],
    ask: "Kalau kamu menjadi bagian dari tim yang akan mempublikasikan pengumuman tersebut, apa keputusan yang paling tepat?",
    choices: [
      { text: "Menurutku teksnya tetap bisa digunakan karena maksudnya sudah jelas dan bentuk bahasanya juga sudah terlihat resmi.", tone: "mid",
        fb: "Alasannya masuk akal — maksudnya memang jelas dan bentuknya resmi. Tapi justru \u201Ckelihatan resmi\u201D yang membuatnya jarang diperiksa ulang. Padahal teks ini membawa nama sekolah dan akan dibaca banyak orang: siswa, guru, bahkan orang tua." },
      { text: "Menurutku teksnya sebaiknya dibuat lebih singkat dulu. Kalau terlalu panjang, pembaca bisa kesulitan memahami informasi yang diberikan.", tone: "mid",
        fb: "Meringkas memang bisa membantu keterbacaan, tapi pertanyaannya bukan soal panjang-pendek.\n\nKalau ejaan, pilihan kata, dan susunan kalimatnya masih keliru, teks yang dipendekkan tetap keliru — dan justru lebih mudah salah paham karena konteksnya berkurang.\n\nPengumuman sekolah bukan tempat untuk menyederhanakan masalah; yang dibutuhkan adalah pemeriksaan yang lebih teliti, bukan pengurangan kata.\n\nNaya mungkin sudah menemukan cara cepat menghasilkan teks panjang. Tapi kecepatan tanpa ketelitian justru menciptakan masalah baru: teks yang terlihat lengkap namun belum tentu benar.\n\nKesadaran terhadap norma bahasa bukan tentang membuat teks lebih pendek atau lebih panjang. Ini tentang berhenti sejenak dan bertanya: 'Sudahkah saya benar-benar memastikan setiap kata, ejaan, dan susunan kalimatnya tepat sebelum dibaca banyak orang?'" },
      { text: "Menurutku kita periksa lagi sebelum dipublikasikan, bukan hanya melihat apakah bahasanya terlihat resmi, tetapi juga mengecek ejaan, pilihan kata, susunan kalimat, dan kejelasan informasinya.", tone: "good",
        fb: "Alya benar untuk mempertanyakan satu hal penting:\n\nBahasa yang terlihat resmi belum tentu otomatis benar.\n\nKadang kita menganggap sebuah tulisan sudah tepat hanya karena: bahasanya panjang, menggunakan kata-kata formal, atau terlihat seperti pengumuman resmi.\n\nPadahal, bentuk yang terlihat resmi masih perlu diperiksa.\n\nAda perbedaan antara \u201Ckelihatan resmi\u201D dan \u201Cmemang sudah tepat\u201D.\n\nKesadaran terhadap norma bukan berarti mencari-cari kesalahan orang lain.\n\nJustru dimulai dari kebiasaan sederhana: berhenti sebentar, membaca ulang, dan memastikan apa yang kita tulis memang sudah tepat sebelum dibaca banyak orang.\n\nApalagi ketika tulisan tersebut membawa nama sekolah." },
      { text: "Menurutku semua kalimatnya perlu diubah menjadi lebih baku supaya benar-benar sesuai dengan gaya pengumuman resmi sekolah.", tone: "mid",
        fb: "Makin baku bukan jaminan makin benar — justru kadang kaidahnya makin ketat. Yang dibutuhkan bukan gaya yang lebih formal, tapi pemeriksaan yang lebih jujur sebelum terbit. Baku itu gaya; tepat itu syarat." },
    ],
    reflect: "Pernah nggak kamu mengirim sesuatu hanya karena kelihatannya sudah benar? Biasanya kamu memeriksa apa — dan apa yang terlewat?",
  },
  {
    id: "ch4",
    place: "Rumah Naya · Malam, Sambil Scroll Medsos",
    title: "Gue ngomong begini karena apa, ya?",
    domain: "CODE-MIXING AWARENESS",
    msgs: [
      { from: "Naya", side: "l", text: "Eh gue tadi kan baca baca proposal penelitian OPSI punya Larisa sama Nazwa ya" },
      { from: "Raka", side: "l", text: "Terus?" },
      { from: "Naya", side: "l", text: "TERUS gue baru nyadar sesuatu gitu" },
      { from: "Naya", side: "l", text: "Gue sekarang sering banget ngomong 'literally', 'imagine', 'scroll', 'slow living', 'ngecrushin orang', 'healing' padahal gue gatau arti jelasnya apaan hehe, modal tau dari medsos gue mah." },
      { from: "Raka", side: "l", text: "Bukannya biasa aja ya? Maksud gue, yang penting lo tau kata kata itu bisa dipake pas momen apa." },
      { from: "Naya", side: "l", text: "Emang biasa sih.." },
      { from: "Naya", side: "l", text: "Cuma tadi gue ngomong sama adek gue, terus kepikiran... kalau gue gatau Bahasa Indonesianya, ngapain gue pake? DAN KAYAK.. biar mencerminkan orang indo banget nih, kenapa gue ga pake kosakata bahasa indonesia aja? daripada pake kosakata bahasa asing" },
      { from: "Naya", side: "l", text: "Setara bule kah gue?😭" },
      { from: "Alya", side: "l", text: "WKWKWKW. Yaa...karena udah kebiasaan mungkin." },
      { from: "Naya", side: "l", text: "Nah. Justru itu alya.." },
      { from: "Raka", side: "l", text: "Terus menurut lo masalahnya apaa? emang lo bisa langsung berbahasa indonesia yang baik dan bener?? kalo kata gue mah sulit yak" },
      { from: "Naya", side: "l", text: "Hmm.. belum tau sih.." },
    ],
    ask: "Apa yang paling penting untuk disadari dari situasi Naya?",
    choices: [
      { text: "Kalau sebuah istilah sudah sering muncul di media sosial, wajar saja digunakan dalam percakapan sehari-hari karena bahasa memang terus berkembang.", tone: "mid",
        fb: "Benar bahwa bahasa berkembang dan itu wajar. Tapi kata \u201Cwajar\u201D kadang dipakai untuk menutup pertanyaan. Naya justru sedang menyadari sesuatu yang jarang disadari orang — dan momen seperti itu seharusnya diikuti, bukan ditutup dengan \u201Cya sudah wajar\u201D." },
      { text: "Kalau ada padanan Bahasa Indonesia yang bisa digunakan, sebaiknya istilah asing tersebut selalu diganti agar penggunaan Bahasa Indonesia tetap terjaga.", tone: "mid",
        fb: "Niat menjaga Bahasa Indonesia memang terlihat tulus. Tapi kalau alasan utamanya adalah aturan — bahwa bahasa asing harus diganti — maka yang berubah hanya permukaannya.\n\nKebiasaan memakai kata asing tanpa berpikir panjang tidak hilang, hanya tersembunyi di balik penggantian kata.\n\nPertanyaan yang lebih jujur bukan 'Bolehkah pakai kata asing?' tapi 'Kenapa gue lebih dulu memakai kata asing ketika ada padanan yang bisa dipahami semua orang?'\n\nKesadaran yang tumbuh dari pertanyaan itu yang mengubah kebiasaan, bukan daftar larangan.\n\nNaya sendiri sudah menyadari bahwa dia menggunakan kata-kata seperti 'literally' dan 'imagine' tanpa benar-benar mengetahui maknanya. Itu bukan masalah kosakata — itu masalah kebiasaan yang belum pernah dipertanyakan.\n\nDan ketika sebuah kebiasaan belum pernah dipertanyakan, mengganti kata satu per satu tidak akan mengubah pola di baliknya." },
      { text: "Yang perlu diperhatikan bukan hanya asal sebuah kata, tetapi apakah kita memahami maknanya dan memang memilihnya karena sesuai dengan maksud serta situasinya.", tone: "good",
        fb: "Mengikuti perkembangan bahasa bukan sesuatu yang otomatis salah.\n\nMedia sosial memang membuat kata dan ungkapan baru menyebar dengan sangat cepat.\n\nMasalahnya muncul ketika kita menggunakan sesuatu hanya karena sudah terbiasa melihat orang lain menggunakannya, tanpa lagi memperhatikan makna atau situasinya.\n\nJadi pertanyaannya bukan: \u201CBoleh nggak pakai kata asing?\u201D\n\nTetapi: \u201CGue tahu nggak kenapa gue pakai kata itu?\u201D\n\nKalau kita sadar terhadap pilihan sendiri, kita tidak sekadar mengikuti bahasa yang sedang lewat di timeline." },
      { text: "Penggunaan istilah asing sebaiknya dibatasi karena kebiasaan tersebut lama-kelamaan dapat membuat orang lebih terbiasa dengan bahasa asing.", tone: "mid",
        fb: "Kekhawatiran ini nyata dan tidak bisa dianggap enteng. Tapi membatasi tanpa menyadari alasan hanya memindahkan kebiasaan, bukan menumbuhkan kesadaran. Naya sudah satu langkah lebih jauh dari sekadar dibatasi: dia mulai bertanya pada dirinya sendiri." },
    ],
    reflect: "Coba sebut satu kata asing yang sering kamu pakai. Kalau ditanya arti persisnya dan padanan Indonesia-nya, bisa langsung jawab?",
  },
  {
    id: "ch5",
    place: "Ruang Diskusi Proyek · Antar Sekolah",
    title: "Biar semua ngerti.",
    domain: "CONTEXT AWARENESS",
    msgs: [
      { from: "Ajo", side: "l", text: "Guys, anak-anak dari SMA luar udah pada kumpul." },
      { from: "Naya", side: "l", text: "Yang dari Kalimantan tadi ngobrol pakai bahasa daerah terus kan?" },
      { from: "Alya", side: "l", text: "Iya, sama temennya." },
      { from: "Naya", side: "l", text: "Jujur.. gue gapaham banget lagi mereka ngomong apa😭" },
      { from: "Ajo", side: "l", text: "Wajar sih, mereka kan udah biasa ngomong kaya gitu" },
      { from: "Alya", side: "l", text: "Terus pas diskusi proyek gimana?" },
      { from: "Bian", side: "l", text: "Banyak yang ga nyambung. Mereka semua kebanyakan masih pake bahasa daerah, ada yang keselip Bahasa Sunda lah, Jawa, Banjar, terus.. ah sisanya ga inget gue" },
      { from: "Naya", side: "l", text: "Berarti kita suruh pakai mereka pake Bahasa Indonesia semua, gaboleh campur bahasa daerah?" },
      { from: "Alya", side: "l", text: "Menurut lo?" },
    ],
    ask: "Keputusan mana yang paling tepat untuk situasi tersebut?",
    choices: [
      { text: "Kalau sedang mengerjakan proyek bersama, sebaiknya semua orang menggunakan Bahasa Indonesia supaya pembicaraan bisa dipahami oleh seluruh anggota.", tone: "mid",
        fb: "Tujuannya bagus: semua paham. Tapi cara \u201Csemua wajib Bahasa Indonesia terus\u201D bisa terdengar seperti melarang bahasa daerah — padahal teman-teman baru itu juga berhak nyaman dengan bahasa mereka saat santai. Ada ruang untuk keduanya, asal fungsinya jelas." },
      { text: "Menurutku bahasa daerah tetap boleh digunakan ketika berbicara dengan teman yang memahaminya, tetapi ketika seluruh kelompok perlu terlibat, sebaiknya menggunakan bahasa yang dapat dipahami bersama.", tone: "good",
        fb: "Bahasa daerah tidak menjadi masalah hanya karena tidak semua orang memahaminya.\n\nJustru keberadaan banyak bahasa merupakan bagian dari keberagaman Indonesia.\n\nYang menjadi persoalan adalah ketika sebuah kelompok harus bekerja bersama, tetapi sebagian anggotanya tidak dapat mengikuti pembicaraan.\n\nDi situ Bahasa Indonesia memiliki fungsi penting: bukan untuk menggantikan bahasa daerah, tetapi untuk menjadi bahasa yang dapat mempertemukan orang-orang dengan latar belakang bahasa yang berbeda.\n\nJadi menghargai Bahasa Indonesia tidak berarti harus mengurangi penghargaan terhadap bahasa daerah.\n\nKeduanya bisa berjalan bersama." },
      { text: "Kalau tujuan utamanya supaya tidak ada yang merasa tertinggal, lebih baik semua orang menggunakan satu bahasa yang sama sejak awal.", tone: "mid",
        fb: "Niatnya sama: tidak ada yang tertinggal. Tapi \u201Csatu bahasa sejak awal\u201D yang dipaksakan bisa membuat teman baru merasa bahasa mereka dianggap salah. Yang dibutuhkan adalah kesepakatan bersama, bukan tekanan dari satu pihak." },
      { text: "Menurutku tidak perlu dipermasalahkan. Kalau ada yang tidak mengerti, mereka bisa bertanya sendiri ketika pembicaraan sudah selesai.", tone: "bad",
        fb: "Ini yang paling perlu dihindari. \u201CNanti tanya sendiri\u201D kedengaran ringan, tapi efeknya: sebagian anggota dibiarkan di luar percakapan sampai selesai. Proyek bersama butuh semua orang ikut memahami sambil berjalan, bukan mencari tahu setelah keputusan diambil." },
    ],
    reflect: "Kalau kamu yang jadi salah satu anak Kalimantan di situ, apa yang kamu harapkan dari kelompokmu?",
  },
  {
    id: "ch6",
    place: "Kelas · Jam Istirahat",
    title: "Internasional?",
    domain: "LANGUAGE ATTITUDE",
    msgs: [
      { from: "Maiu", side: "l", text: "I mean, gue ngerti sih kenapa kalian suka yang ini, but personally gue masih kurang convinced. I think bagian awalnya too much, terus pas masuk ke inti malah jadi kurang fokus. Maybe we should keep it simple aja biar orang nggak langsung lose interest." },
      { from: "Naya", side: "l", text: "Lu orang mana sih? ngomong kok campur campur gitu." },
      { from: "Maiu", side: "l", text: "Orang Indo lah, gue kan dari dulu sekolah internasional, baru kali ini pindah ke sekolah negeri. Soo.. ga terbiasa aja full Indo, gue juga udah nyaman kaya gini sih." },
      { from: "Naya", side: "l", text: "Nyaman sih nyaman, tapi lu kan tinggal dan lahir di Indonesia.. yakali lu kebiasaan sampe nanti ngomong kaya gitu, padahal lu bule aja bukan? masa lu krisis bahasa cuma gara gara kelamaan sekolah internasional? lu gaada niatan buat membiasakan berbahasa yang baik emang?" },
      { from: "Maiu", side: "l", text: "Hmm.. i think.. nanti aja deh niatnya✌🏻" },
    ],
    ask: "Setelah membaca percakapan Maiu dan Naya, menurutmu apa yang paling perlu diperhatikan dari situasi tersebut?",
    choices: [
      { text: "Maiu sebaiknya mulai lebih sering menggunakan Bahasa Indonesia, terutama setelah pindah ke lingkungan baru. Kebiasaan berbahasa dari sekolah sebelumnya tetap bisa dipertahankan, tetapi jangan sampai membuatnya sulit menyesuaikan diri.", tone: "mid",
        fb: "Seimbang di permukaan: kebiasaan lama dipertahankan, penyesuaian tetap jalan. Tapi coba dengar jawaban Maiu sendiri: \u201Cnanti aja deh niatnya.\u201D Tanpa sadar kenapa penyesuaian itu perlu, \u201Cnanti\u201D biasanya berarti tidak pernah." },
      { text: "Cara bicara Maiu sebenarnya tidak menjadi masalah selama orang-orang di sekitarnya masih memahami maksudnya. Bahasa memang berkembang dari kebiasaan, jadi tidak perlu terlalu mempermasalahkan campuran bahasa dalam percakapan sehari-hari.", tone: "mid",
        fb: "'Selama dipahami tidak masalah' memang terdengar masuk akal. Tapi komunikasi bukan sekadar soal pesan sampai — bahasa juga cara kita menempatkan diri di lingkungan baru.\n\nMaiu baru saja pindah ke sekolah negeri dari lingkungan internasional. Kalau dia terus berbicara seperti di lingkungan lamanya tanpa pernah menyesuaikan, yang terjadi bukan pertumbuhan — melainkan kenyamanan yang menggantikan kesadaran.\n\nBahasa yang berkembang adalah bahasa yang mampu menyesuaikan, bukan bahasa yang menolak berubah.\n\nAda perbedaan antara 'Gue memang terbiasa menggunakan bahasa seperti ini' dan 'Gue tidak perlu mengembangkan cara berbahasa yang lain karena gue sudah nyaman.' Yang pertama adalah kebiasaan. Yang kedua mulai menunjukkan sikap.\n\nDan ketika seseorang lebih memilih tetap nyaman daripada belajar menyesuaikan, yang hilang bukan kemampuan berbahasanya — melainkan kemauannya untuk bertumbuh." },
      { text: "Maiu tidak perlu meninggalkan kebiasaan menggunakan Bahasa Inggris, tetapi penting untuk menyadari bahwa rasa nyaman tidak seharusnya menjadi alasan untuk berhenti mengembangkan kemampuan Bahasa Indonesia dan menyesuaikannya dengan situasi.", tone: "good",
        fb: "Campur bahasa dalam percakapan sehari-hari tidak otomatis berarti seseorang tidak menghargai Bahasa Indonesia.\n\nKebiasaan berbahasa bisa terbentuk dari lingkungan, pergaulan, media, bahkan pengalaman pendidikan. Seseorang yang sejak lama berada di lingkungan yang banyak menggunakan Bahasa Inggris tentu bisa terbiasa mencampurkan kedua bahasa tersebut dalam percakapan.\n\nNamun, rasa nyaman tidak selalu berarti pilihan tersebut sudah tepat untuk setiap situasi.\n\nAda perbedaan antara \u201CGue memang terbiasa menggunakan bahasa seperti ini.\u201D dan \u201CGue tidak perlu mengembangkan cara berbahasa yang lain karena gue sudah nyaman.\u201D\n\nYang pertama adalah kebiasaan.\n\nYang kedua mulai menunjukkan sikap.\n\nBahasa Indonesia tidak seharusnya dianggap sebagai sesuatu yang hanya perlu digunakan ketika ada aturan yang memaksa. Kemampuan untuk menggunakan Bahasa Indonesia dengan baik juga perlu tetap berkembang, meskipun seseorang menguasai atau terbiasa menggunakan bahasa lain.\n\nDi sisi lain, menghargai Bahasa Indonesia juga bukan berarti harus meninggalkan Bahasa Inggris.\n\nBahasa Inggris tetap memiliki tempatnya. Bahasa Indonesia juga memiliki tempatnya.\n\nYang penting adalah kemampuan untuk menyesuaikan penggunaan bahasa tanpa menganggap salah satunya lebih rendah.\n\nKarena pada akhirnya, persoalannya bukan: \u201CBoleh nggak mencampur bahasa?\u201D\n\nTetapi: \u201CApakah kita masih punya pilihan, atau kita hanya mengikuti kebiasaan?\u201D\n\nKetika seseorang mampu menggunakan bahasa lain tetapi tetap percaya diri dan mampu menggunakan Bahasa Indonesia dengan baik sesuai konteks, penggunaan bahasa tidak lagi sekadar mengikuti kebiasaan.\n\nItu sudah menjadi pilihan yang sadar." },
      { text: "Karena Maiu lahir dan tinggal di Indonesia, ia seharusnya membiasakan diri menggunakan Bahasa Indonesia sepenuhnya. Bahasa Inggris tetap dapat digunakan dalam situasi tertentu, tetapi jangan sampai menjadi kebiasaan dalam percakapan sehari-hari.", tone: "mid",
        fb: "Kebanggaan pada Bahasa Indonesia terasa di sini. Tapi \u201Cwajib full Indonesia\u201D justru menutup ruang: Bahasa Inggris tetap punya fungsinya. Yang jadi persoalan bukan Bahasa Inggrisnya Maiu, tapi kalimat penutupnya: \u201Cnanti aja deh niatnya\u201D — di situ sikapnya terlihat." },
    ],
    reflect: "Maiu bilang \u201Cnyaman sih nyaman\u201D. Menurutmu, kenyamanan itu alasan yang cukup, atau baru titik mulai?",
  },
  {
    id: "ch7",
    place: "Grup Sahabat · Dini Hari",
    title: "Puitis",
    domain: "LANGUAGE ATTITUDE",
    msgs: [
      { from: "Dina", side: "l", text: "ciee ada yang lagi falling in love ni yee @raka" },
      { from: "Alya", side: "l", text: "CIEE rakaa" },
      { from: "Naya", side: "l", text: "raka udah gedeee🥺" },
      { from: "Raka", side: "l", text: "APAANN" },
      { from: "Raka", side: "l", text: "tau darimana dinn. 🙄" },
      { from: "Dina", side: "l", text: "mengirim tangkapan layar repost-an Raka", img: true },
      { from: "Dina", side: "l", text: "repostannya kaya pujangga lagi kecintaan semua lagi wkwkw" },
      { from: "Dina", side: "l", text: "sok puitis euy" },
      { from: "Raka", side: "l", text: "lah kok sok puitis??" },
      { from: "Raka", side: "l", text: "kata kata indah itu boyy" },
      { from: "Dina", side: "l", text: "tetep aja rakaa, sok puitis ah. kaya sok iya gitu." },
      { from: "Raka", side: "l", text: "yeuu dari pada repostan lu, sok inggris semua" },
      { from: "Dina", side: "l", text: "yang penting ga alay kaya repostan lu yang sok puitis itu😛" },
    ],
    ask: "Kalau kamu ada di posisi Raka, respons mana yang paling tepat untuk menanggapi Dina?",
    choices: [
      { text: "Wkwk yaudah, selera kita emang beda, Din. Lu nyaman repost yang pakai Bahasa Inggris, gue nyaman sama tulisan yang puitis. Ga harus ada yang lebih bagus dari yang lain kok.", tone: "mid",
        fb: "Respons ini damai dan dewasa — tidak ada yang direndahkan. Tapi ada satu hal yang belum tersentuh: Dina barusan menyebut tulisanmu \u201Calay\u201D dan \u201Csok puitis\u201D. Bilang \u201Cyaudah selera beda\u201D itu damai, tapi label yang menurunkan itu dibiarkan berdiri tanpa dibantah." },
      { text: "Kalau menurut lu puitis itu alay, ya gapapa. Tapi jangan sampai karena lu lebih suka kata kata yang pakai Bahasa Inggris, tulisan Bahasa Indonesia yang puitis jadi lu anggap alayy, bahasa kita sendiri loh itu, Din.", tone: "mid",
        fb: "Arahnya berani — menegaskan bahwa Bahasa Indonesia sendiri tidak boleh direndahkan hanya karena dianggap 'alay'. Tapi ada satu hal yang perlu diperhatikan: ketika kita membalas dengan nada yang sama persis seperti yang kita kritik, kita justru sedang melakukan hal yang sama — memberi label pada selera orang lain.\n\nDina menyerang selera Raka dengan label 'alay'. Raka membalas dengan menyerang selera Dina. Siapa pun yang menang dalam pertukaran seperti ini, yang kalah adalah ruang untuk saling memahami.\n\nPesan yang kuat tidak harus disampaikan dengan nada yang sama kuatnya. Kadang yang paling berbobot justru yang disampaikan tanpa harus menyerang balik.\n\nYang lebih penting untuk diperhatikan bukan siapa yang lebih benar, tapi mengapa kita cenderung merendahkan pilihan bahasa orang lain hanya karena berbeda dari pilihan kita sendiri. Label 'alay', 'sok puitis', 'sok Inggris' — semua itu lahir dari kebiasaan memberi nilai pada cara orang berbahasa. Dan kebiasaan itu tidak akan berhenti hanya karena kita membalasnya dengan nada yang sama." },
      { text: "Kayaknya kita malah sama-sama ngatain satu sama lain sok sok an deh, Din. Gue suka kata kata puitis begini karena emang menurut gue makna nya tuh lebih nyampe, dan indah gitu loh..estetik. Kalo lu suka teks yang pake bahasa asing, ya itu urusan selera lu. Gausah ngatain selera guee, Dinn.", tone: "good",
        fb: "Yang terjadi di chat tadi sebenarnya bukan cuma soal Raka suka tulisan puitis atau Dina suka menggunakan Bahasa Inggris.\n\nMereka sama-sama mulai memberi label pada pilihan bahasa orang lain:\n\u201Csok puitis.\u201D\n\u201Csok Inggris.\u201D\n\u201Calay.\u201D\n\nPadahal, suka atau tidak suka terhadap suatu gaya bahasa adalah hal yang wajar. Yang perlu dipikirkan adalah ketika selera pribadi mulai dipakai untuk menentukan apakah cara orang lain berbahasa itu lebih rendah atau lebih baik.\n\nRaka bisa saja memang menyukai kata-kata puitis.\n\nDina juga bisa saja lebih nyaman menggunakan istilah Bahasa Inggris.\n\nTidak ada yang otomatis lebih keren hanya karena terdengar modern. Begitu juga tidak ada yang otomatis lebih baik hanya karena menggunakan Bahasa Indonesia.\n\nYang lebih penting justru alasan di balik pilihan itu.\n\nApakah memang sesuai dengan yang ingin disampaikan? Apakah karena sudah terbiasa? Apakah karena lingkungan? Atau karena kita merasa gaya tertentu akan membuat kita terlihat lebih keren?\n\nDi titik ini, kesadaran berbahasa bukan berarti harus memilih satu gaya dan meninggalkan gaya lainnya.\n\nJustru kita belajar untuk tidak mudah merendahkan pilihan bahasa orang lain hanya karena berbeda dari pilihan kita sendiri.\n\nKarena menghargai Bahasa Indonesia juga bukan berarti harus mengatakan bahwa bahasa lain itu buruk.\n\nDan menggunakan bahasa lain juga tidak seharusnya membuat kita merasa Bahasa Indonesia kurang bernilai.\n\nYang perlu berubah bukan gaya bicaramu.\n\nYang perlu berubah adalah cara kamu memandang pilihan bahasa.\n\n\u201CBeda cara menyampaikan, bukan berarti salah satu harus lebih rendah.\u201D" },
      { text: "Gue sih tetap suka tulisan yang puitis. Menurut gue Bahasa Indonesia memang punya banyak cara buat menyampaikan sesuatu dengan indah. Tapi gue juga ga masalah kalau lu lebih suka pakai Bahasa Inggris, selama itu memang sesuatu yang lu suka.", tone: "mid",
        fb: "Pilihan ini tenang dan tidak menyerang — bagus. Tapi coba dengar lagi: kamu membelakan dirimu (\u201Cgue sih tetap suka\u201D) tanpa pernah menyentuh label \u201Csok puitis\u201D dan \u201Calay\u201D yang barusan dilempar. Kadang diam pada label membuat label itu terasa benar — bukan cuma buat kamu, tapi buat yang membacanya." },
    ],
    reflect: "Pernah nggak kamu memberi label pada gaya bahasa orang lain — sok, alay, kuno? Dari mana label itu pertama kali kamu dengar?",
  },
  {
    id: "ch8",
    place: "Grup Panitia · Akhir Malam",
    title: "Kalau Semua Memilih yang Sama?",
    domain: "LANGUAGE AGENCY",
    msgs: [
      { from: "Alya", side: "l", text: "Guys, bentar." },
      { from: "Raka", side: "l", text: "Apaan?" },
      { from: "Alya", side: "l", text: "Gue baru lihat caption di postingan beberapa kelompok lain." },
      { from: "Naya", side: "l", text: "Kenapa?" },
      { from: "Alya", side: "l", text: "Hampir semuanya pakai Bahasa Inggris." },
      { from: "Raka", side: "l", text: "Ya emang kenapa? 😭" },
      { from: "Alya", side: "l", text: "Gue juga nggak masalah sama Inggrisnya." },
      { from: "Alya", side: "l", text: "Cuma jadi kepikiran ajaa.." },
      { from: "Naya", side: "l", text: "Kepikiran apaan?" },
      { from: "Alya", side: "l", text: "Kalau semua orang terus milih bahasa yang dianggap lebih keren…" },
      { from: "Alya", side: "l", text: "lama-lama kita sendiri bakal nganggep Bahasa Indonesia yang baik dan benar, Bahasa Indonesia yang baku, atau Bahasa Indonesia yang puitis itu kurang menarik, atau malah sampe nganggep ketinggalan zaman, parah banget ga sih?" },
      { from: "Raka", side: "l", text: "Duh kejauhan, Al. Kan ini cuma caption." },
      { from: "Naya", side: "l", text: "Nahh, gue juga awalnya mikir gitu." },
      { from: "Naya", side: "l", text: "Tapi kalau kejadian kaya gini malah terjadi terus menerus, gimana?" },
      { from: "Raka", side: "l", text: "Terus menurut kalian kita harus selalu pakai Bahasa Indonesia?" },
      { from: "Alya", side: "l", text: "Bukan itu." },
      { from: "Alya", side: "l", text: "Gue cuma pengen tau…" },
      { from: "Alya", side: "l", text: "kalau kita bebas memilih, sebenarnya bahasa mana dan apa yang mau kita pertahankan?" },
      { from: "Naya", side: "l", text: "…" },
      { from: "Raka", side: "l", text: "Duh." },
      { from: "Raka", side: "l", text: "Berat, Al." },
      { from: "Naya", side: "l", text: "Bahkan gue baru sadar selama ini gue sering milih kata karena udah terbiasa." },
      { from: "Naya", side: "l", text: "Atau karena takut kelihatan biasa." },
      { from: "Alya", side: "l", text: "Bisa juga karena pengen kelihatan berwawasan internasional." },
      { from: "Naya", side: "l", text: "IYA BANGET LAGI." },
      { from: "Raka", side: "l", text: "Terus sekarang?" },
      { from: "Naya", side: "l", text: "Sekarang gue malah mikir... kita sebenarnya harus punya prinsip nggak sih soal bahasa yang kita pakai?" },
      { from: "Alya", side: "l", text: "Kalau menurut lo?" },
    ],
    ask: "Kalau kita memang bebas memilih bahasa, menurutmu apa yang seharusnya menjadi pertimbangan utama sebelum kita memilih sebuah bahasa?",
    choices: [
      { text: "Yang penting bahasa itu membuat kita terlihat modern dan bisa mengikuti perkembangan zaman.", tone: "bad",
        fb: "Tapi coba berhenti sebentar.\n\nKalau \u201Cterlihat modern\u201D menjadi alasan utama, apakah kita benar-benar sedang memilih bahasa — atau sedang mengikuti standar sosial tentang bahasa mana yang dianggap lebih berkelas?\n\nBahasa akan terus berkembang. Menggunakan bahasa asing bukan masalah. Yang perlu dipertanyakan adalah ketika nilai sebuah bahasa mulai diukur dari gengsinya, bukan dari fungsi dan konteksnya." },
      { text: "Yang paling penting adalah menggunakan bahasa yang paling mudah dipahami. Selama pesannya sampai, berarti pilihan bahasanya sudah tepat.", tone: "mid",
        fb: "Komunikasi yang efektif memang penting, tapi bahasa tidak hanya menyampaikan informasi — bahasa juga membawa identitas, kebiasaan, dan cara kita memandang dunia.\n\nKetika kita hanya bertanya 'Apakah orang lain mengerti?', kita berhenti di permukaan. Pertanyaan yang lebih dalam adalah 'Mengapa gue memilih cara mengatakan ini?'\n\nKarena bisa jadi pilihan bahasa kita selama ini bukan lahir dari kebutuhan, tapi dari anggapan yang sudah tertanam tanpa pernah dipertanyakan.\n\nDan kalau kita tidak pernah mempertanyakan alasan di balik pilihan kita, seberapa bebas sebenarnya pilihan itu?\n\nAlya barusan mengajak semua orang untuk berhenti sejenak dan bertanya: 'Kalau kita bebas memilih bahasa, sebenarnya bahasa mana dan apa yang mau kita pertahankan?' Itu bukan pertanyaan tentang boleh atau tidak menggunakan bahasa tertentu. Itu pertanyaan tentang kesadaran — apakah pilihan kita lahir dari pemahaman atau hanya dari kebiasaan yang belum pernah kita sangkal." },
      { text: "Kalau Bahasa Indonesia adalah bahasa kita sendiri, seharusnya kita lebih mengutamakannya daripada bahasa asing.", tone: "mid",
        fb: "Memiliki sikap positif terhadap Bahasa Indonesia memang penting. Tetapi mencintai bahasa sendiri tidak harus berarti menolak bahasa lain.\n\nJustru kalau kita berpikir bahwa Bahasa Indonesia hanya bisa dipertahankan dengan menghindari Bahasa Inggris, kita masih melihat persoalan ini sebagai pilihan \u201CIndonesia atau asing.\u201D\n\nPadahal persoalannya jauh lebih dalam:\n\nApakah kita masih mampu memilih bahasa berdasarkan kebutuhan dan konteks, tanpa menganggap bahasa tertentu otomatis lebih tinggi daripada yang lain?" },
      { text: "Menurutku, kita memang bebas memilih bahasa. Tapi kebebasan itu harus disertai kesadaran: kenapa kita memilih bahasa ini, dalam konteks apa, dan apakah pilihan kita lahir dari kebutuhan atau dari anggapan bahwa bahasa tertentu lebih keren?", tone: "good",
        fb: "Nah. Ini inti persoalannya.\n\nMasalahnya bukan ketika seseorang menggunakan Bahasa Inggris.\n\nMasalahnya muncul ketika kita berhenti menyadari alasan di balik pilihan tersebut.\n\nKita bisa mencampur bahasa. Kita bisa menggunakan Bahasa Inggris. Kita juga bisa memilih Bahasa Indonesia yang baku, santai, atau bahkan puitis.\n\nTidak ada satu bahasa yang harus digunakan dalam semua keadaan.\n\nTetapi ketika kita mulai memilih sebuah bahasa hanya karena takut terlihat biasa, ingin dianggap berwawasan internasional, atau merasa bahasa sendiri kurang keren — di situlah kita perlu berhenti dan bertanya:\n\n\u201CIni benar-benar pilihan gue, atau gue cuma mengikuti apa yang dianggap keren oleh lingkungan gue?\u201D\n\nKarena pada akhirnya, loyal terhadap bahasa bukan berarti menutup diri dari bahasa lain.\n\nLoyalitas berarti tetap menghargai dan memberi tempat pada bahasa sendiri, bahkan ketika bahasa lain terlihat lebih bergengsi.\n\n\u201CKita sering berpikir bahwa kita bebas memilih bahasa. Tapi apakah kita benar-benar bebas, kalau pilihan kita diam-diam ditentukan oleh apa yang dianggap keren?\u201D\n\nBahasa boleh berubah. Cara kita menggunakannya boleh berkembang. Tapi jangan sampai tanpa sadar, kita ikut mengubah cara kita memandang bahasa kita sendiri.\n\n\u201CGue boleh berkembang mengikuti zaman. Tapi gue nggak perlu kehilangan rasa bangga terhadap bahasa gue sendiri.\u201D" },
    ],
    reflect: "\u201CBahasa itu pilihan. Dan pilihan gue punya alasan.\u201D — Kalau begitu, apa alasan di balik pilihan bahasamu hari ini?",
  },
];
