from pathlib import Path
from shutil import copyfile

from docx import Document


SOURCE = Path("prima_revisi_HIGH_HUMANIZED.docx")
OUT = Path("prima_revisi_HIGH_HUMANIZED_V2.docx")


REPLACEMENTS = {
    "Bahasa Indonesia memegang peran penting dalam kehidupan bangsa. Ia tidak hanya menjadi alat komunikasi, tetapi juga menjadi bahasa persatuan, bahasa pendidikan, dan penanda identitas kebangsaan. Bagi remaja, bahasa juga berfungsi sebagai cara untuk menunjukkan kedekatan kelompok, membangun citra diri, dan berpartisipasi di ruang digital. Oleh sebab itu, upaya menguatkan loyalitas terhadap bahasa Indonesia sebaiknya tidak berhenti pada hafalan kaidah, tetapi diarahkan pada tumbuhnya kesadaran untuk memilih ragam bahasa yang tepat sesuai situasi.": "Di lingkungan sekolah, bahasa Indonesia sebenarnya hadir hampir di semua kegiatan siswa: saat belajar di kelas, berdiskusi dengan teman, menulis tugas, mengikuti organisasi, sampai membuat unggahan di media sosial. Namun, cara siswa menggunakan bahasa tidak selalu sama pada setiap situasi. Ada saatnya mereka memakai bahasa yang lebih santai, ada saatnya mereka perlu memakai bahasa Indonesia yang lebih tertib dan jelas. Karena itu, loyalitas terhadap bahasa Indonesia tidak cukup dipahami sebagai kewajiban memakai bahasa baku terus-menerus, tetapi sebagai kesadaran untuk memilih bahasa yang tepat sesuai tempat, tujuan, dan lawan bicara.",
    "Perkembangan media sosial membuat cara berkomunikasi remaja semakin cepat, ringkas, dan variatif. Dalam percakapan digital, mereka sering memakai slang, emotikon, campur kode Indonesia-Inggris, serta istilah populer seperti happy, healing, deadline, vibes, atau relate. Fenomena seperti ini tidak dapat langsung disebut sebagai kesalahan, sebab variasi bahasa merupakan bagian dari dinamika sosial. Persoalan baru muncul ketika remaja belum mampu membedakan kapan bahasa santai dapat digunakan, kapan campur kode masih wajar, dan kapan bahasa Indonesia yang lebih sesuai norma perlu dipilih.": "Di media sosial, remaja terbiasa menulis dengan gaya yang cepat dan ringkas. Mereka memakai slang, emotikon, campur kode Indonesia-Inggris, serta istilah seperti happy, healing, deadline, vibes, atau relate. Gaya seperti ini tidak selalu salah karena bahasa memang berubah mengikuti lingkungan pemakainya. Akan tetapi, kebiasaan tersebut dapat menjadi masalah ketika siswa tidak lagi peka terhadap perbedaan situasi. Bahasa untuk story Instagram tentu tidak selalu cocok dipakai untuk menulis laporan, pengumuman kelas, atau komunikasi resmi di sekolah.",
    "Kebutuhan penguatan bahasa Indonesia pada pelajar juga memiliki dasar empiris. Balai Bahasa Provinsi Jambi (2025) menjelaskan bahwa UKBI digunakan sebagai instrumen strategis untuk mendorong kemahiran berbahasa Indonesia yang terstandar. Data pelajar tahun 2024 yang disoroti dalam laporan tersebut menunjukkan bahwa pembinaan kemahiran berbahasa masih perlu diperkuat. Dengan demikian, pembinaan bahasa Indonesia bagi pelajar perlu dirancang dengan cara yang lebih dekat dengan dunia mereka, termasuk kebiasaan berkomunikasi di ruang digital.": "Kebutuhan untuk menguatkan kemampuan berbahasa Indonesia pada pelajar juga tampak dari data kebahasaan. Balai Bahasa Provinsi Jambi (2025) menjelaskan bahwa UKBI digunakan sebagai alat untuk melihat kemahiran berbahasa Indonesia secara lebih terstandar. Data pelajar tahun 2024 yang disoroti dalam laporan tersebut menunjukkan bahwa pembinaan kemahiran berbahasa masih perlu diperkuat. Artinya, pembinaan bahasa Indonesia perlu dibuat lebih dekat dengan kebiasaan siswa hari ini, termasuk kebiasaan mereka berkomunikasi melalui media digital.",
    "Pendekatan kesadaran berbahasa atau language awareness menjadi relevan karena menekankan kepekaan terhadap bentuk, fungsi, konteks, dan dampak sosial penggunaan bahasa (Carter, 2003; Fairclough, 1992). Melalui pendekatan ini, remaja tidak sekadar diberi larangan untuk memakai campur kode atau bahasa gaul. Mereka justru diajak melihat alasan di balik pilihan bahasa, memahami konteks pemakaiannya, lalu mengambil keputusan berbahasa secara lebih sadar. Cara pandang ini lebih adil secara sosiolinguistik dan lebih dekat dengan kenyataan komunikasi remaja saat ini.": "Pendekatan kesadaran berbahasa atau language awareness sesuai dengan masalah tersebut karena tidak langsung menghakimi cara berbahasa remaja. Pendekatan ini mengajak siswa memperhatikan bentuk bahasa, fungsi bahasa, konteks pemakaian, dan dampak sosial dari pilihan kata yang mereka gunakan (Carter, 2003; Fairclough, 1992). Dengan pendekatan ini, siswa tidak hanya diberi tahu bahwa bahasa tertentu benar atau salah, tetapi diajak memahami mengapa suatu pilihan bahasa cocok untuk satu situasi dan kurang cocok untuk situasi lain.",
    "Berdasarkan persoalan tersebut, penelitian ini menawarkan PRIMA+ sebagai platform digital berbasis kesadaran berbahasa. Platform ini dirancang sebagai media interaktif yang memadukan contoh kasus bahasa digital, kuis kontekstual, refleksi pilihan bahasa, sistem skor, dan umpan balik. Dengan demikian, penelitian ini tidak hanya menghasilkan sebuah produk, tetapi juga menguji sejauh mana PRIMA+ dapat membantu menguatkan loyalitas bahasa Indonesia remaja secara terukur.": "Berdasarkan keadaan tersebut, penelitian ini mengembangkan PRIMA+ sebagai media digital untuk melatih kesadaran berbahasa siswa. PRIMA+ memuat contoh kasus bahasa digital, kuis kontekstual, refleksi pilihan bahasa, sistem skor, dan umpan balik. Melalui platform ini, siswa diharapkan tidak hanya menjawab soal, tetapi juga belajar menimbang pilihan bahasa yang mereka gunakan. Penelitian ini kemudian menguji apakah penggunaan PRIMA+ dapat membantu menguatkan loyalitas bahasa Indonesia remaja secara terukur.",
    "Celah utama penelitian ini terletak pada masih terbatasnya model penguatan loyalitas bahasa Indonesia remaja yang menghubungkan kesadaran berbahasa dengan media digital interaktif. Kajian tentang campur kode dan bahasa digital umumnya lebih banyak menjelaskan fenomena, sedangkan penelitian gamifikasi bahasa sering berfokus pada pembelajaran bahasa asing. PRIMA+ ditempatkan untuk menjembatani celah tersebut, yaitu sebagai platform yang membantu remaja memahami konteks, menumbuhkan kebanggaan, dan mempertahankan penggunaan bahasa Indonesia secara lebih sadar.": "Penelitian ini berangkat dari celah sederhana tetapi penting. Banyak tulisan sudah membahas campur kode, bahasa gaul, dan perubahan bahasa di media sosial. Di sisi lain, penelitian tentang gamifikasi bahasa lebih sering membahas pembelajaran bahasa asing. Masih belum banyak model yang secara khusus menghubungkan kesadaran berbahasa, loyalitas bahasa Indonesia, dan media digital interaktif untuk remaja. PRIMA+ dikembangkan untuk mengisi ruang tersebut.",
    "Secara teoretis, penelitian ini diharapkan memperkaya kajian sosiolinguistik terapan dan pembelajaran bahasa Indonesia. Kontribusinya terutama terletak pada pengembangan media digital yang tidak hanya mengajarkan kaidah bahasa, tetapi juga menumbuhkan sikap, kesadaran, dan loyalitas berbahasa.": "Secara teoretis, penelitian ini diharapkan menambah contoh penerapan kajian sosiolinguistik dalam pembelajaran bahasa Indonesia. Penelitian ini juga menunjukkan bahwa media digital dapat dipakai bukan hanya untuk melatih pengetahuan kaidah bahasa, tetapi juga untuk membangun sikap dan kesadaran berbahasa.",
    "Bagi siswa, PRIMA+ diharapkan membantu mereka memahami penggunaan bahasa Indonesia secara lebih sadar, kontekstual, dan tetap relevan dengan kebiasaan komunikasi digital.": "Bagi siswa, PRIMA+ diharapkan membantu mereka lebih peka saat menggunakan bahasa Indonesia, terutama ketika berpindah dari ruang santai di media sosial ke situasi yang lebih resmi di sekolah.",
    "Bagi guru Bahasa Indonesia, PRIMA+ dapat menjadi contoh media pembelajaran sikap bahasa yang memadukan materi, latihan, dan pengambilan keputusan berbahasa dalam situasi yang dekat dengan kehidupan siswa.": "Bagi guru Bahasa Indonesia, PRIMA+ dapat menjadi contoh media pembelajaran yang mengaitkan materi bahasa dengan situasi nyata yang sering ditemui siswa.",
    "Bagi sekolah, penelitian ini dapat mendukung program literasi, pembentukan karakter kebahasaan, dan penguatan identitas nasional melalui kegiatan yang lebih dekat dengan budaya digital siswa.": "Bagi sekolah, penelitian ini dapat mendukung program literasi dan pembiasaan berbahasa Indonesia yang lebih dekat dengan keseharian siswa.",
    "Bagi pengembang media pendidikan, penelitian ini memberi gambaran awal mengenai rancangan produk digital yang dapat dikembangkan lebih lanjut untuk pembelajaran bahasa Indonesia.": "Bagi pengembang media pendidikan, penelitian ini dapat menjadi rancangan awal untuk membuat media belajar bahasa Indonesia yang lebih interaktif.",
    "Ruang digital membuat komunikasi remaja berlangsung cepat, multimodal, dan penuh variasi. Kajian internet linguistics menunjukkan bahwa teknologi digital dapat mengubah praktik bahasa, pola interaksi, dan norma komunikasi (Crystal, 2011). Dalam konteks Indonesia, penggunaan bahasa gaul dan campur kode di media sosial perlu dipahami sebagai gejala sosial, sekaligus sebagai tantangan bagi pembinaan bahasa Indonesia.": "Komunikasi remaja di ruang digital berlangsung cepat dan sering memadukan teks, gambar, suara, emotikon, serta video. Crystal (2011) menjelaskan bahwa teknologi digital dapat mengubah praktik bahasa, pola interaksi, dan norma komunikasi. Dalam konteks Indonesia, bahasa gaul dan campur kode di media sosial perlu dilihat sebagai gejala sosial. Namun, gejala tersebut tetap menjadi tantangan bagi pembinaan bahasa Indonesia, terutama ketika siswa belum mampu menyesuaikan bahasa dengan konteksnya.",
    "Kesadaran berbahasa menekankan kepekaan terhadap struktur, fungsi, konteks, dan konsekuensi sosial dari penggunaan bahasa. Carter (2003) memandang language awareness sebagai peningkatan kesadaran terhadap bentuk dan fungsi bahasa, sedangkan Fairclough (1992) menekankan dimensi kritis bahasa dalam relasi sosial. Dalam penelitian ini, kesadaran berbahasa diarahkan pada kemampuan siswa menilai pilihan bahasa dalam konteks formal, informal, sekolah, dan media sosial.": "Kesadaran berbahasa menekankan kemampuan seseorang untuk memperhatikan bentuk, fungsi, konteks, dan akibat sosial dari bahasa yang digunakan. Carter (2003) memandang language awareness sebagai kesadaran terhadap bentuk dan fungsi bahasa, sedangkan Fairclough (1992) menekankan pentingnya sikap kritis dalam melihat hubungan bahasa dan kehidupan sosial. Dalam penelitian ini, kesadaran berbahasa diarahkan pada kemampuan siswa menilai pilihan bahasa dalam konteks formal, informal, sekolah, dan media sosial.",
    "Loyalitas bahasa dapat dipahami sebagai sikap untuk mempertahankan dan menggunakan bahasa sebagai bagian dari identitas sosial. Garvin dan Mathiot (1968) menempatkan loyalitas bahasa sebagai salah satu unsur sikap bahasa, bersama kebanggaan bahasa dan kesadaran terhadap norma. Dalam penelitian ini, loyalitas bahasa Indonesia tidak dimaknai sebagai penolakan mutlak terhadap bahasa asing atau bahasa gaul. Loyalitas dimaknai sebagai kemampuan dan kemauan untuk menjaga fungsi bahasa Indonesia secara tepat sesuai konteks.": "Loyalitas bahasa dapat dipahami sebagai kemauan untuk tetap menggunakan dan menjaga bahasa sebagai bagian dari identitas sosial. Garvin dan Mathiot (1968) menempatkan loyalitas bahasa sebagai salah satu unsur sikap bahasa, bersama kebanggaan bahasa dan kesadaran terhadap norma. Dalam penelitian ini, loyalitas bahasa Indonesia tidak berarti menolak semua bahasa asing atau bahasa gaul. Loyalitas lebih dipahami sebagai kemauan untuk tetap menempatkan bahasa Indonesia secara tepat, terutama pada situasi yang memang membutuhkan bahasa Indonesia yang jelas dan tertib.",
    "Gamifikasi memanfaatkan unsur permainan, seperti poin, tantangan, misi, umpan balik, dan capaian, untuk meningkatkan keterlibatan belajar. Beberapa tinjauan sistematis menunjukkan bahwa gamifikasi dapat mendukung motivasi belajar bahasa, meskipun efektivitasnya sangat bergantung pada desain pedagogis, kualitas umpan balik, dan cara mengukur hasil belajar (Al-Dosakee & Ozdamli, 2021; Luo, 2023; Shortt et al., 2021). Oleh karena itu, PRIMA+ tidak cukup hanya dibuat menarik secara tampilan. Platform ini juga perlu memiliki indikator, instrumen, dan mekanisme evaluasi yang jelas.": "Gamifikasi memanfaatkan unsur permainan, seperti poin, tantangan, misi, umpan balik, dan capaian, agar proses belajar terasa lebih menarik. Beberapa tinjauan sistematis menunjukkan bahwa gamifikasi dapat mendukung motivasi belajar bahasa, meskipun hasilnya tetap bergantung pada desain pembelajaran, kualitas umpan balik, dan cara mengukur capaian belajar (Al-Dosakee & Ozdamli, 2021; Luo, 2023; Shortt et al., 2021). Karena itu, PRIMA+ tidak cukup hanya dibuat menarik. Platform ini juga perlu memiliki tujuan, indikator, instrumen, dan evaluasi yang jelas.",
    "Penelitian ini menggunakan metode Research and Development (R&D) dengan model ADDIE, yaitu Analyze, Design, Develop, Implement, dan Evaluate (Branch, 2009). Model ini dipilih karena sesuai untuk penelitian yang menghasilkan dan menguji sebuah produk pembelajaran. Untuk melihat efektivitas PRIMA+, penelitian menggunakan desain one-group pretest-posttest. Desain tersebut dianggap sesuai karena penelitian berfokus pada pengembangan prototipe dan uji coba terbatas, bukan pada perbandingan antarkelas dalam skala besar.": "Penelitian ini menggunakan metode Research and Development (R&D) dengan model ADDIE, yaitu Analyze, Design, Develop, Implement, dan Evaluate (Branch, 2009). Model ADDIE dipilih karena tahapannya membantu peneliti mengembangkan produk secara bertahap, mulai dari membaca kebutuhan siswa sampai mengevaluasi hasil uji coba. Untuk melihat efektivitas PRIMA+, penelitian ini menggunakan desain one-group pretest-posttest. Desain tersebut sesuai karena penelitian masih berada pada tahap pengembangan prototipe dan uji coba terbatas.",
    "Penelitian direncanakan berlangsung pada April-Agustus 2026 di MAN Kotawaringin Timur, Kalimantan Tengah. Kegiatannya mencakup analisis kebutuhan, perancangan, pengembangan prototipe, validasi, uji coba terbatas, analisis data, revisi produk, dan penyusunan laporan akhir.": "Penelitian direncanakan berlangsung pada April-Agustus 2026 di MAN Kotawaringin Timur, Kalimantan Tengah. Selama rentang waktu tersebut, kegiatan penelitian dimulai dari analisis kebutuhan, perancangan, pengembangan prototipe, validasi, uji coba terbatas, analisis data, revisi produk, hingga penyusunan laporan akhir.",
    "Subjek penelitian adalah siswa MAN Kotawaringin Timur kelas X atau XI yang aktif menggunakan media digital. Uji coba terbatas direncanakan melibatkan 30-40 siswa agar data pretest-posttest yang diperoleh lebih stabil dibandingkan uji coba dengan jumlah responden yang sangat kecil. Teknik pengambilan sampel menggunakan purposive sampling, dengan kriteria siswa aktif, bersedia mengikuti rangkaian penelitian, memiliki akses perangkat untuk mencoba platform, dan memperoleh izin sesuai ketentuan sekolah.": "Subjek penelitian adalah siswa MAN Kotawaringin Timur kelas X atau XI yang aktif menggunakan media digital. Uji coba terbatas direncanakan melibatkan 30-40 siswa. Jumlah ini dipilih agar data pretest-posttest lebih memadai dibandingkan uji coba dengan responden yang terlalu sedikit. Sampel ditentukan secara purposive, yaitu siswa yang aktif, bersedia mengikuti rangkaian penelitian, memiliki akses perangkat untuk mencoba platform, dan memperoleh izin sesuai ketentuan sekolah.",
    "Prosedur penelitian disusun dengan model ADDIE agar hubungan antara pengembangan produk, validasi, uji coba, dan evaluasi terlihat lebih runtut.": "Prosedur penelitian disusun dengan model ADDIE agar proses pengembangan PRIMA+ terlihat runtut, mulai dari membaca kebutuhan siswa sampai melakukan evaluasi dan revisi akhir.",
    "Data dianalisis dengan pendekatan kuantitatif dan kualitatif sederhana. Data validasi ahli dihitung dalam bentuk persentase kelayakan. Data pretest dan posttest dianalisis melalui rata-rata, persentase peningkatan, dan N-gain. Jika data memenuhi syarat, peningkatan skor diuji menggunakan paired sample t-test; apabila syarat tersebut tidak terpenuhi, digunakan uji Wilcoxon. Sementara itu, refleksi siswa dianalisis secara tematik ringkas untuk menjelaskan pengalaman, kendala, dan saran pengguna.": "Data dianalisis secara kuantitatif dan kualitatif sederhana. Hasil validasi ahli dihitung dalam bentuk persentase kelayakan. Skor pretest dan posttest dibandingkan melalui rata-rata, persentase peningkatan, dan N-gain. Jika data memenuhi syarat, peningkatan skor diuji dengan paired sample t-test. Jika syarat tersebut tidak terpenuhi, digunakan uji Wilcoxon. Refleksi siswa kemudian dibaca secara tematik untuk melihat pengalaman, kendala, dan saran mereka setelah menggunakan PRIMA+.",
    "Total anggaran sebesar Rp10.000.000 dipilih agar kebutuhan pengembangan prototipe dan uji coba dapat terpenuhi secara realistis, tetapi tetap berada di bawah batas maksimal Rp15.000.000. Godot Engine atau perangkat lunak open-source tidak dihitung sebagai biaya lisensi. Anggaran lebih diarahkan pada pembuatan prototipe, penyediaan aset, penyusunan instrumen, pelaksanaan uji coba, validasi, dan dokumentasi.": "Total anggaran dirancang sebesar Rp10.000.000. Jumlah ini dipilih karena masih berada di bawah batas maksimal Rp15.000.000, tetapi sudah cukup untuk mendukung pengembangan prototipe dan uji coba terbatas. Godot Engine atau perangkat lunak open-source tidak dihitung sebagai biaya lisensi. Anggaran diarahkan pada pembuatan prototipe, penyediaan aset, penyusunan instrumen, pelaksanaan uji coba, validasi, dan dokumentasi.",
    "Penelitian ini menggunakan bantuan Artificial Intelligence (AI), yaitu Gemini dan ChatGPT, secara terbatas untuk mencari referensi awal, memperdalam teori, merapikan kerangka metodologi, dan menyusun alternatif alur permainan atau kuis bahasa. Meskipun demikian, seluruh keputusan penelitian, penyusunan instrumen, pengembangan produk, pengambilan data, analisis data, dan penarikan kesimpulan tetap dilakukan oleh peneliti. AI tidak digunakan untuk membuat data palsu, menggantikan proses uji coba, atau menulis hasil penelitian tanpa verifikasi.": "Penelitian ini menggunakan bantuan Artificial Intelligence (AI), yaitu Gemini dan ChatGPT, secara terbatas. AI digunakan untuk membantu mencari referensi awal, memahami teori, merapikan kerangka metodologi, dan mencari alternatif ide alur permainan atau kuis bahasa. Namun, keputusan penelitian, penyusunan instrumen, pengembangan produk, pengambilan data, analisis data, dan penarikan kesimpulan tetap dilakukan oleh peneliti. AI tidak digunakan untuk membuat data palsu, menggantikan proses uji coba, atau menulis hasil penelitian tanpa verifikasi.",
}


def replace_paragraph_text(paragraph, new_text):
    for run in paragraph.runs:
        run.text = ""
    if paragraph.runs:
        paragraph.runs[0].text = new_text
    else:
        paragraph.add_run(new_text)


def main():
    if not SOURCE.exists():
        raise FileNotFoundError(SOURCE)
    copyfile(SOURCE, OUT)
    doc = Document(str(OUT))
    count = 0
    for paragraph in doc.paragraphs:
        old = paragraph.text.strip()
        if old in REPLACEMENTS:
            replace_paragraph_text(paragraph, REPLACEMENTS[old])
            count += 1
    doc.save(str(OUT))
    print(f"wrote {OUT} replacements={count}")


if __name__ == "__main__":
    main()
