from pathlib import Path
from shutil import copyfile

from docx import Document


SOURCE = Path("prima_revisi_HIGH_REVIEW.docx")
OUT = Path("prima_revisi_HIGH_HUMANIZED.docx")


REPLACEMENTS = {
    "Bahasa Indonesia memiliki fungsi strategis sebagai bahasa nasional, bahasa persatuan, bahasa pendidikan, dan penanda identitas kebangsaan. Pada kalangan remaja, bahasa Indonesia tidak hanya dipakai untuk menyampaikan pesan, tetapi juga untuk membentuk identitas sosial, menunjukkan kedekatan kelompok, dan berpartisipasi dalam ruang digital. Karena itu, penguatan loyalitas bahasa Indonesia perlu diarahkan bukan hanya pada hafalan kaidah, tetapi juga pada kesadaran memilih ragam bahasa sesuai konteks.": "Bahasa Indonesia memegang peran penting dalam kehidupan bangsa. Ia tidak hanya menjadi alat komunikasi, tetapi juga menjadi bahasa persatuan, bahasa pendidikan, dan penanda identitas kebangsaan. Bagi remaja, bahasa juga berfungsi sebagai cara untuk menunjukkan kedekatan kelompok, membangun citra diri, dan berpartisipasi di ruang digital. Oleh sebab itu, upaya menguatkan loyalitas terhadap bahasa Indonesia sebaiknya tidak berhenti pada hafalan kaidah, tetapi diarahkan pada tumbuhnya kesadaran untuk memilih ragam bahasa yang tepat sesuai situasi.",
    "Perkembangan media sosial mengubah pola komunikasi remaja. Ungkapan singkat, slang, emotikon, campur kode Indonesia-Inggris, dan istilah populer seperti happy, healing, deadline, vibes, atau relate sering muncul dalam percakapan digital. Fenomena ini tidak boleh disederhanakan sebagai kesalahan semata karena variasi bahasa merupakan gejala sosiolinguistik yang wajar. Namun, masalah penelitian muncul ketika remaja tidak memiliki kesadaran untuk membedakan kapan bahasa santai, campur kode, bahasa baku, dan bahasa Indonesia yang sesuai norma perlu digunakan.": "Perkembangan media sosial membuat cara berkomunikasi remaja semakin cepat, ringkas, dan variatif. Dalam percakapan digital, mereka sering memakai slang, emotikon, campur kode Indonesia-Inggris, serta istilah populer seperti happy, healing, deadline, vibes, atau relate. Fenomena seperti ini tidak dapat langsung disebut sebagai kesalahan, sebab variasi bahasa merupakan bagian dari dinamika sosial. Persoalan baru muncul ketika remaja belum mampu membedakan kapan bahasa santai dapat digunakan, kapan campur kode masih wajar, dan kapan bahasa Indonesia yang lebih sesuai norma perlu dipilih.",
    "Kebutuhan penguatan bahasa Indonesia pada pelajar juga memiliki dasar empiris. Balai Bahasa Provinsi Jambi (2025) melaporkan pemanfaatan UKBI sebagai instrumen strategis untuk mewujudkan kemahiran berbahasa Indonesia yang terstandar, serta menyoroti bahwa data pelajar tahun 2024 masih menunjukkan kebutuhan penguatan kemahiran berbahasa. Temuan ini memperlihatkan bahwa pembinaan bahasa Indonesia pada kelompok pelajar perlu terus dikembangkan melalui strategi yang dekat dengan kehidupan digital mereka.": "Kebutuhan penguatan bahasa Indonesia pada pelajar juga memiliki dasar empiris. Balai Bahasa Provinsi Jambi (2025) menjelaskan bahwa UKBI digunakan sebagai instrumen strategis untuk mendorong kemahiran berbahasa Indonesia yang terstandar. Data pelajar tahun 2024 yang disoroti dalam laporan tersebut menunjukkan bahwa pembinaan kemahiran berbahasa masih perlu diperkuat. Dengan demikian, pembinaan bahasa Indonesia bagi pelajar perlu dirancang dengan cara yang lebih dekat dengan dunia mereka, termasuk kebiasaan berkomunikasi di ruang digital.",
    "Pendekatan kesadaran berbahasa atau language awareness relevan karena menekankan kepekaan terhadap bentuk, fungsi, konteks, dan dampak sosial penggunaan bahasa (Carter, 2003; Fairclough, 1992). Dengan pendekatan ini, remaja tidak sekadar diberi larangan memakai campur kode atau bahasa gaul, tetapi diajak memahami fungsi bahasa, menilai konteks, dan mengambil keputusan kebahasaan secara sadar. Pendekatan tersebut lebih adil secara sosiolinguistik dan lebih dekat dengan realitas komunikasi remaja.": "Pendekatan kesadaran berbahasa atau language awareness menjadi relevan karena menekankan kepekaan terhadap bentuk, fungsi, konteks, dan dampak sosial penggunaan bahasa (Carter, 2003; Fairclough, 1992). Melalui pendekatan ini, remaja tidak sekadar diberi larangan untuk memakai campur kode atau bahasa gaul. Mereka justru diajak melihat alasan di balik pilihan bahasa, memahami konteks pemakaiannya, lalu mengambil keputusan berbahasa secara lebih sadar. Cara pandang ini lebih adil secara sosiolinguistik dan lebih dekat dengan kenyataan komunikasi remaja saat ini.",
    "Berdasarkan persoalan tersebut, penelitian ini mengembangkan PRIMA+ sebagai platform digital berbasis kesadaran berbahasa. PRIMA+ dirancang sebagai media interaktif yang memadukan contoh kasus bahasa digital, kuis kontekstual, refleksi pilihan bahasa, sistem skor, dan umpan balik. Penelitian ini tidak hanya bertujuan membuat produk, tetapi juga menguji apakah penggunaan PRIMA+ dapat menguatkan loyalitas bahasa Indonesia remaja secara terukur.": "Berdasarkan persoalan tersebut, penelitian ini menawarkan PRIMA+ sebagai platform digital berbasis kesadaran berbahasa. Platform ini dirancang sebagai media interaktif yang memadukan contoh kasus bahasa digital, kuis kontekstual, refleksi pilihan bahasa, sistem skor, dan umpan balik. Dengan demikian, penelitian ini tidak hanya menghasilkan sebuah produk, tetapi juga menguji sejauh mana PRIMA+ dapat membantu menguatkan loyalitas bahasa Indonesia remaja secara terukur.",
    "Gap utama penelitian ini adalah belum kuatnya model penguatan loyalitas bahasa Indonesia remaja yang menghubungkan pendekatan kesadaran berbahasa dengan media digital interaktif. Kajian tentang campur kode dan bahasa digital umumnya menjelaskan fenomena, sedangkan kajian gamifikasi bahasa banyak berfokus pada pembelajaran bahasa asing. PRIMA+ ditempatkan sebagai upaya mengisi celah tersebut melalui platform yang menumbuhkan kesadaran konteks, kebanggaan, dan kesetiaan penggunaan bahasa Indonesia.": "Celah utama penelitian ini terletak pada masih terbatasnya model penguatan loyalitas bahasa Indonesia remaja yang menghubungkan kesadaran berbahasa dengan media digital interaktif. Kajian tentang campur kode dan bahasa digital umumnya lebih banyak menjelaskan fenomena, sedangkan penelitian gamifikasi bahasa sering berfokus pada pembelajaran bahasa asing. PRIMA+ ditempatkan untuk menjembatani celah tersebut, yaitu sebagai platform yang membantu remaja memahami konteks, menumbuhkan kebanggaan, dan mempertahankan penggunaan bahasa Indonesia secara lebih sadar.",
    "Penelitian ini memperkaya kajian sosiolinguistik terapan dan pembelajaran bahasa Indonesia, terutama pada pengembangan media digital berbasis kesadaran berbahasa untuk menguatkan sikap dan loyalitas bahasa.": "Secara teoretis, penelitian ini diharapkan memperkaya kajian sosiolinguistik terapan dan pembelajaran bahasa Indonesia. Kontribusinya terutama terletak pada pengembangan media digital yang tidak hanya mengajarkan kaidah bahasa, tetapi juga menumbuhkan sikap, kesadaran, dan loyalitas berbahasa.",
    "Bagi siswa, PRIMA+ membantu memahami penggunaan bahasa Indonesia secara sadar, kontekstual, dan tetap relevan dengan ruang digital.": "Bagi siswa, PRIMA+ diharapkan membantu mereka memahami penggunaan bahasa Indonesia secara lebih sadar, kontekstual, dan tetap relevan dengan kebiasaan komunikasi digital.",
    "Bagi guru Bahasa Indonesia, PRIMA+ dapat menjadi contoh media pembelajaran sikap bahasa yang tidak hanya berisi materi kaidah, tetapi juga latihan pengambilan keputusan berbahasa.": "Bagi guru Bahasa Indonesia, PRIMA+ dapat menjadi contoh media pembelajaran sikap bahasa yang memadukan materi, latihan, dan pengambilan keputusan berbahasa dalam situasi yang dekat dengan kehidupan siswa.",
    "Bagi sekolah, penelitian ini dapat mendukung program literasi, karakter kebahasaan, dan penguatan identitas nasional.": "Bagi sekolah, penelitian ini dapat mendukung program literasi, pembentukan karakter kebahasaan, dan penguatan identitas nasional melalui kegiatan yang lebih dekat dengan budaya digital siswa.",
    "Bagi pengembang media pendidikan, penelitian ini memberi rancangan awal produk digital yang dapat dikembangkan lebih lanjut.": "Bagi pengembang media pendidikan, penelitian ini memberi gambaran awal mengenai rancangan produk digital yang dapat dikembangkan lebih lanjut untuk pembelajaran bahasa Indonesia.",
    "Penelitian dilakukan pada uji coba terbatas di MAN Kotawaringin Timur.": "Penelitian ini dibatasi pada uji coba terbatas di MAN Kotawaringin Timur.",
    "Produk PRIMA+ difokuskan pada prototipe pembelajaran interaktif, bukan aplikasi komersial penuh.": "Produk PRIMA+ dalam penelitian ini masih difokuskan sebagai prototipe pembelajaran interaktif, belum sebagai aplikasi komersial yang lengkap.",
    "Loyalitas bahasa Indonesia diukur melalui indikator sikap dan perilaku berbahasa yang dapat diamati melalui kuesioner, tes skenario, dan aktivitas platform.": "Loyalitas bahasa Indonesia diukur melalui indikator sikap dan perilaku berbahasa yang dapat diamati lewat kuesioner, tes skenario, serta aktivitas siswa saat menggunakan platform.",
    "Data empiris lokal tidak diasumsikan sebelum pengambilan data; data lokal akan diperoleh melalui survei kebutuhan, pretest, posttest, dan refleksi pengguna.": "Data empiris lokal tidak diasumsikan sejak awal. Data tersebut akan diperoleh melalui survei kebutuhan, pretest, posttest, dan refleksi pengguna selama proses penelitian.",
    "Ruang digital membuat komunikasi remaja berlangsung cepat, multimodal, dan penuh variasi. Kajian internet linguistics menjelaskan bahwa teknologi digital dapat mengubah praktik bahasa, bentuk interaksi, dan norma komunikasi (Crystal, 2011). Dalam konteks Indonesia, penggunaan bahasa gaul dan campur kode di media sosial perlu dipahami sebagai gejala sosial sekaligus tantangan pembinaan bahasa.": "Ruang digital membuat komunikasi remaja berlangsung cepat, multimodal, dan penuh variasi. Kajian internet linguistics menunjukkan bahwa teknologi digital dapat mengubah praktik bahasa, pola interaksi, dan norma komunikasi (Crystal, 2011). Dalam konteks Indonesia, penggunaan bahasa gaul dan campur kode di media sosial perlu dipahami sebagai gejala sosial, sekaligus sebagai tantangan bagi pembinaan bahasa Indonesia.",
    "Kesadaran berbahasa menekankan kepekaan terhadap struktur, fungsi, konteks, dan konsekuensi sosial bahasa. Carter (2003) menjelaskan language awareness sebagai peningkatan kesadaran terhadap bentuk dan fungsi bahasa, sedangkan Fairclough (1992) menekankan dimensi kritis bahasa dalam relasi sosial. Pada penelitian ini, kesadaran berbahasa diarahkan pada kemampuan siswa menilai pilihan bahasa dalam konteks formal, informal, sekolah, dan media sosial.": "Kesadaran berbahasa menekankan kepekaan terhadap struktur, fungsi, konteks, dan konsekuensi sosial dari penggunaan bahasa. Carter (2003) memandang language awareness sebagai peningkatan kesadaran terhadap bentuk dan fungsi bahasa, sedangkan Fairclough (1992) menekankan dimensi kritis bahasa dalam relasi sosial. Dalam penelitian ini, kesadaran berbahasa diarahkan pada kemampuan siswa menilai pilihan bahasa dalam konteks formal, informal, sekolah, dan media sosial.",
    "Loyalitas bahasa merupakan sikap mempertahankan dan menggunakan bahasa sebagai bagian dari identitas sosial. Garvin dan Mathiot (1968) menempatkan loyalitas bahasa sebagai unsur sikap bahasa, bersama kebanggaan bahasa dan kesadaran norma. Dalam konteks penelitian ini, loyalitas bahasa Indonesia tidak dimaknai sebagai penolakan total terhadap bahasa asing atau bahasa gaul, melainkan sebagai kemampuan dan kemauan menjaga fungsi bahasa Indonesia secara tepat sesuai konteks.": "Loyalitas bahasa dapat dipahami sebagai sikap untuk mempertahankan dan menggunakan bahasa sebagai bagian dari identitas sosial. Garvin dan Mathiot (1968) menempatkan loyalitas bahasa sebagai salah satu unsur sikap bahasa, bersama kebanggaan bahasa dan kesadaran terhadap norma. Dalam penelitian ini, loyalitas bahasa Indonesia tidak dimaknai sebagai penolakan mutlak terhadap bahasa asing atau bahasa gaul. Loyalitas dimaknai sebagai kemampuan dan kemauan untuk menjaga fungsi bahasa Indonesia secara tepat sesuai konteks.",
    "Gamifikasi menggunakan elemen permainan seperti poin, tantangan, misi, umpan balik, dan capaian untuk meningkatkan keterlibatan belajar. Tinjauan sistematis menunjukkan bahwa gamifikasi dapat mendukung motivasi belajar bahasa, tetapi efektivitasnya bergantung pada desain pedagogis, kualitas umpan balik, dan cara pengukuran hasil belajar (Al-Dosakee & Ozdamli, 2021; Luo, 2023; Shortt et al., 2021). Karena itu, PRIMA+ tidak cukup hanya dibuat menarik, tetapi harus memiliki indikator, instrumen, dan mekanisme evaluasi yang jelas.": "Gamifikasi memanfaatkan unsur permainan, seperti poin, tantangan, misi, umpan balik, dan capaian, untuk meningkatkan keterlibatan belajar. Beberapa tinjauan sistematis menunjukkan bahwa gamifikasi dapat mendukung motivasi belajar bahasa, meskipun efektivitasnya sangat bergantung pada desain pedagogis, kualitas umpan balik, dan cara mengukur hasil belajar (Al-Dosakee & Ozdamli, 2021; Luo, 2023; Shortt et al., 2021). Oleh karena itu, PRIMA+ tidak cukup hanya dibuat menarik secara tampilan. Platform ini juga perlu memiliki indikator, instrumen, dan mekanisme evaluasi yang jelas.",
    "Penelitian ini menggunakan metode Research and Development (R&D) dengan model ADDIE yang terdiri atas Analyze, Design, Develop, Implement, dan Evaluate (Branch, 2009). Untuk menguji efektivitas produk, penelitian menggunakan desain one-group pretest-posttest. Desain ini dipilih karena penelitian berfokus pada pengembangan prototipe dan uji coba terbatas, bukan perbandingan antarkelas secara luas.": "Penelitian ini menggunakan metode Research and Development (R&D) dengan model ADDIE, yaitu Analyze, Design, Develop, Implement, dan Evaluate (Branch, 2009). Model ini dipilih karena sesuai untuk penelitian yang menghasilkan dan menguji sebuah produk pembelajaran. Untuk melihat efektivitas PRIMA+, penelitian menggunakan desain one-group pretest-posttest. Desain tersebut dianggap sesuai karena penelitian berfokus pada pengembangan prototipe dan uji coba terbatas, bukan pada perbandingan antarkelas dalam skala besar.",
    "Penelitian dilaksanakan pada April-Agustus 2026 di MAN Kotawaringin Timur, Kalimantan Tengah. Tahapan penelitian meliputi analisis kebutuhan, perancangan, pengembangan prototipe, validasi, uji coba terbatas, analisis data, revisi produk, dan penyusunan laporan.": "Penelitian direncanakan berlangsung pada April-Agustus 2026 di MAN Kotawaringin Timur, Kalimantan Tengah. Kegiatannya mencakup analisis kebutuhan, perancangan, pengembangan prototipe, validasi, uji coba terbatas, analisis data, revisi produk, dan penyusunan laporan akhir.",
    "Subjek penelitian adalah siswa MAN Kotawaringin Timur kelas X atau XI yang aktif menggunakan media digital. Uji coba terbatas direncanakan melibatkan 30-40 siswa agar data pretest-posttest lebih stabil daripada uji coba sangat kecil. Teknik sampling menggunakan purposive sampling dengan kriteria: siswa aktif, bersedia mengikuti rangkaian penelitian, memiliki akses perangkat untuk mencoba platform, dan memperoleh izin sesuai ketentuan sekolah.": "Subjek penelitian adalah siswa MAN Kotawaringin Timur kelas X atau XI yang aktif menggunakan media digital. Uji coba terbatas direncanakan melibatkan 30-40 siswa agar data pretest-posttest yang diperoleh lebih stabil dibandingkan uji coba dengan jumlah responden yang sangat kecil. Teknik pengambilan sampel menggunakan purposive sampling, dengan kriteria siswa aktif, bersedia mengikuti rangkaian penelitian, memiliki akses perangkat untuk mencoba platform, dan memperoleh izin sesuai ketentuan sekolah.",
    "Prosedur penelitian direvisi menggunakan model ADDIE agar hubungan antara pengembangan produk, validasi, uji coba, dan evaluasi menjadi lebih jelas.": "Prosedur penelitian disusun dengan model ADDIE agar hubungan antara pengembangan produk, validasi, uji coba, dan evaluasi terlihat lebih runtut.",
    "Data dianalisis secara kuantitatif dan kualitatif sederhana. Data validasi ahli dihitung dengan persentase kelayakan. Data pretest-posttest dianalisis melalui rata-rata, persentase peningkatan, dan N-gain. Jika data memenuhi syarat, uji paired sample t-test digunakan; jika tidak, digunakan uji Wilcoxon. Data refleksi siswa dianalisis secara tematik ringkas untuk menjelaskan kendala dan pengalaman pengguna.": "Data dianalisis dengan pendekatan kuantitatif dan kualitatif sederhana. Data validasi ahli dihitung dalam bentuk persentase kelayakan. Data pretest dan posttest dianalisis melalui rata-rata, persentase peningkatan, dan N-gain. Jika data memenuhi syarat, peningkatan skor diuji menggunakan paired sample t-test; apabila syarat tersebut tidak terpenuhi, digunakan uji Wilcoxon. Sementara itu, refleksi siswa dianalisis secara tematik ringkas untuk menjelaskan pengalaman, kendala, dan saran pengguna.",
    "Produk memperoleh kategori minimal layak dari validator.": "Produk memperoleh kategori minimal layak berdasarkan penilaian validator.",
    "Rata-rata skor posttest lebih tinggi daripada pretest.": "Rata-rata skor posttest lebih tinggi dibandingkan skor pretest.",
    "N-gain minimal berada pada kategori sedang atau menunjukkan peningkatan yang dapat dijelaskan secara akademik.": "Nilai N-gain minimal berada pada kategori sedang, atau setidaknya menunjukkan peningkatan yang dapat dijelaskan secara akademik.",
    "Sebagian besar responden menyatakan PRIMA+ mudah digunakan dan membantu memahami pilihan bahasa sesuai konteks.": "Sebagian besar responden menyatakan bahwa PRIMA+ mudah digunakan dan membantu mereka memahami pilihan bahasa sesuai konteks.",
    "Total anggaran Rp10.000.000 dipilih agar realistis untuk pengembangan prototipe dan uji coba, tetapi tetap berada jauh di bawah batas maksimal Rp15.000.000. Godot Engine atau perangkat lunak open-source tidak dihitung sebagai biaya lisensi; biaya diarahkan pada pembuatan prototipe, aset, instrumen, uji coba, validasi, dan dokumentasi.": "Total anggaran sebesar Rp10.000.000 dipilih agar kebutuhan pengembangan prototipe dan uji coba dapat terpenuhi secara realistis, tetapi tetap berada di bawah batas maksimal Rp15.000.000. Godot Engine atau perangkat lunak open-source tidak dihitung sebagai biaya lisensi. Anggaran lebih diarahkan pada pembuatan prototipe, penyediaan aset, penyusunan instrumen, pelaksanaan uji coba, validasi, dan dokumentasi.",
    "Penelitian ini menggunakan bantuan Artificial Intelligence (AI), yaitu Gemini dan ChatGPT, untuk mencari referensi awal, memperdalam teori, merapikan metodologi, dan menyusun alternatif alur permainan atau kuis bahasa. Seluruh keputusan penelitian, penyusunan instrumen, pengembangan produk, pengambilan data, analisis data, dan penarikan kesimpulan tetap dilakukan secara mandiri oleh peneliti. AI tidak digunakan untuk membuat data palsu, menggantikan uji coba, atau menulis hasil penelitian tanpa verifikasi.": "Penelitian ini menggunakan bantuan Artificial Intelligence (AI), yaitu Gemini dan ChatGPT, secara terbatas untuk mencari referensi awal, memperdalam teori, merapikan kerangka metodologi, dan menyusun alternatif alur permainan atau kuis bahasa. Meskipun demikian, seluruh keputusan penelitian, penyusunan instrumen, pengembangan produk, pengambilan data, analisis data, dan penarikan kesimpulan tetap dilakukan oleh peneliti. AI tidak digunakan untuk membuat data palsu, menggantikan proses uji coba, atau menulis hasil penelitian tanpa verifikasi.",
}


def replace_paragraph_text(paragraph, new_text):
    for run in paragraph.runs:
        run.text = ""
    if paragraph.runs:
        paragraph.runs[0].text = new_text
    else:
        paragraph.add_run(new_text)


def main():
    if not SOURCE.exists():
        raise FileNotFoundError(SOURCE)
    copyfile(SOURCE, OUT)
    doc = Document(str(OUT))
    count = 0
    for paragraph in doc.paragraphs:
        old = paragraph.text.strip()
        if old in REPLACEMENTS:
            replace_paragraph_text(paragraph, REPLACEMENTS[old])
            count += 1
    doc.save(str(OUT))
    print(f"wrote {OUT} replacements={count}")


if __name__ == "__main__":
    main()
